In [8]:
import numpy as np

In [216]:
class Input:
  def __init__(self, File):
    inputs=File.read().split()
    inputs=[int(i) for i in inputs]
    self.v=inputs[0]
    self.u=inputs[1]
    
    self.a_matrix=np.zeros((self.v,self.u)) #Initializing adjacency matrix
    
    self.v_list=[[] for i in range(self.v)] #Initializing adjacency lists
    self.u_list=[[] for i in range(self.u)]
    
    self.s_v_list=[[] for i in range(self.v)] #Initializing second order adjacency lists
    self.s_v_list=[[] for i in range(self.u)]
    
    for i,x in enumerate(inputs[2:]):
        if(x==0):
            continue
        current_v=int(i/self.u)
        current_u=i%self.u
        self.v_list[current_v].append(current_u)
        self.u_list[current_u].append(current_v)
        self.a_matrix[current_v][current_u]=1
    for a,b in enumerate(self.v_list):
        for c in b:
            for d in self.u_list[c]:
                if(d not in self.s_v_list[a]):
                    self.s_v_list[a].append(d)
class Bicluster:
    def __init__(self, v_array,u_array):
        self.v_list=v_array
        self.u_list=u_array
        
class Solution:
    def __init__(self,a_matrix,v_clusters):
        self.a_matrix=a_matrix
        self.v_cluster=v_clusters
    def __init__(self,v,u,v_clusters):
        self.v_cluster=v_clusters
        self.a_matrix=np.zeros((v,u)) 
        for a in v_clusters:
            for b in a.v_list:
                for c in a.u_list:
                    self.a_matrix[b][c]=1
    def evaluate(self,e_a_matrix):
        npm1=np.matrix(e_a_matrix)
        npm2=np.matrix(self.a_matrix)
        return abs(np.matrix((npm1==npm2)-1).sum())
    
    def recomendations(self,e_a_matrix):
        npm1=np.matrix(e_a_matrix)
        npm2=np.matrix(self.a_matrix)
        rec=(npm1==npm2-1)
        rec_list=[]
        for i,x in enumerate(rec):
            for j,y in enumerate(x.flat):
                if(y):
                    rec_list.append([i,j])
        return rec_list

In [217]:
f = open("V_5_U_7_D_0.5_S_1.dat",'r') 
entrada=Input(f)
ex_biclusters=[Bicluster([0,2,3],[3,4,5,6]),Bicluster([1,4],[0,1,2])]
solucao=Solution(entrada.v,entrada.u,ex_biclusters)
print(*entrada.a_matrix,sep='\n')
print("############")
print(*solucao.a_matrix,sep='\n')
solucao.evaluate(entrada.a_matrix)
#print(entrada.a_matrix)
solucao.recomendations(entrada.a_matrix)

[1. 0. 0. 1. 1. 1. 1.]
[0. 1. 1. 1. 1. 1. 0.]
[1. 1. 0. 0. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0.]
[1. 0. 1. 0. 0. 0. 0.]
############
[0. 0. 0. 1. 1. 1. 1.]
[1. 1. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 1. 1. 1.]
[0. 0. 0. 1. 1. 1. 1.]
[1. 1. 1. 0. 0. 0. 0.]


[[1, 0], [2, 3], [2, 4], [2, 6], [3, 4], [3, 6], [4, 1]]